version: '3.7'

services:
    web:
        build: .
        command: bash -c "source .env && python /code/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - 8000:8000
        links:
            - "db:db"
        depends_on:
            - db
    db:
        image: postgres:11
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres